### ISSUE TITLE
テーマとの互換性？

### ISSUE THREAD

**Issue by hayato1207** [technote-space/marker-animation#194]
## Describe the bug: バグの概要

インストールはできましたが、
「重大なエラーを引き起こしたため、プラグインを有効化できませんでした。」と表示されてしまいました。

## Operating environment: バグが発生した環境
 - Version of software
 - OS: [e.g. Windows10]
 - Browser: [e.g. Chrome, Safari]
 - etc.

**Comment by technote-space** [comment]
使用しているテーマは何でしょうか？

**Comment by technote-space** [comment]
WPのバージョンとインストールしているプラグインも分かると原因を特定しやすいのでできれば教えてください。
