### ISSUE TITLE
マーカーアニメーション

### ISSUE THREAD

**Issue by Momos291291** [technote-space/marker-animation#273]
はじめまして、
マーカーアニメーションが気にいって
プラグインをインストールして有効化まで確認したんですが
エディタにボタンが表示されません。
何かお気づきの点ございませんでしょうか？

**Comment by technote-space** [comment]
@Momos291291 
報告ありがとうございます。
使用しているWordPressのバージョンとスクリーンショットを載せてくださると助かります。
スクリーンショットはドラックアンドドロップで追加できます。
