### ISSUE TITLE
`wp_marker_animation___log`なるテーブルを削除しても大丈夫でしょうか？

### ISSUE THREAD

**Issue by yaquawa** [technote-space/marker-animation#358]
恥ずかしながら最近ようやくGutenbergを使いはじめまして、マーカーを引くようなプラグインがないか探してみたところ、こちらにたどり着きました。（渡りに船すぎて泣いた‥！しかも高機能！）開発していただき、本当にありがとうございます！

表題の件ですが、technoteさんが利用しているWPプラグインのフレームワークが勝手に作成したものでしょうか…？
使用されていないみたいなので、削除しても構わないのでしょうか？

ついでに、もう一つお聞きしたいのですが、
こちらのプラグイン、更新するには普通にzipをダウンロードし直せばよいのでしょうかね？

お忙しいところ失礼しました、ご回答お待ちしております。

**Comment by technote-space** [comment]
@yaquawa 
log テーブルはプラグインが作成したものです。
詳細設定でログを有効にしてある場合に使用されます。
主にデバッグ用なので消しても問題ないと思いますが動作確認はしていないので不具合が発生するかもしれません。
テーブルを削除する場合は「ログが有効かどうか」の設定をONにしないでください。
またこのテーブルはプラグイン削除時に削除されます。

**Comment by yaquawa** [comment]
@technote-space なるほど、理解しました。ご回答ありがとうございます！
